"""fix userphoto

Revision ID: 142302e29928
Revises: 1e5c70ed12e8
Create Date: 2024-06-26 11:41:49.651881

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '142302e29928'
down_revision = '1e5c70ed12e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userphoto', sa.Column('recipient_id', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('userphoto', sa.Column('sender_id', sa.Integer(), nullable=False, server_default='1'))
    op.drop_constraint('userphoto_user_id_fkey', 'userphoto', type_='foreignkey')
    op.create_foreign_key(None, 'userphoto', 'user', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'userphoto', 'user', ['recipient_id'], ['id'])
    op.drop_column('userphoto', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userphoto', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'userphoto', type_='foreignkey')
    op.drop_constraint(None, 'userphoto', type_='foreignkey')
    op.create_foreign_key('userphoto_user_id_fkey', 'userphoto', 'user', ['user_id'], ['id'])
    op.drop_column('userphoto', 'sender_id')
    op.drop_column('userphoto', 'recipient_id')
    # ### end Alembic commands ###
